name: SybHideAndSeek
main: me.sybsuper.SybHideAndSeek.Main
version: 1.3.1
commands:
  hideandseek:
    aliases: [hideandseek,has]
    description: Start a Hide & Seek game.
    permission: sybhideandseek.start
    usage: /sybhideandseek
  sound:
    description: Play a sound at your position to get a reward.
    permission: sybhideandseek.sound
    usage: /sound