name: SybHideAndSeek
main: me.sybsuper.SybHideAndSeek.Main
version: 1.4.3
author: Sybsuper
commands:
  hideandseek:
    aliases: [hideandseek,has]
    description: Start a Hide & Seek game.
    permission: sybhideandseek.start
    usage: /sybhideandseek
  sound:
    description: Play a sound at your position to get a reward.
    permission: sybhideandseek.sound
    usage: /sound
permissions:
  sybhideandseek.start:
    default: op
    description: Gives you access to the /hideandseek command
  sybhideandseek.sound:
    default: op
    description: Gives you access to the /sound command.